site_name: chmpy
site_url: https://peterspackman.github.io/chmpy/
repo_url: https://github.com/peterspackman/chmpy
repo_name: peterspackman/chmpy

theme:
    name: material
    palette:
        primary: light blue
        scheme: preference
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/peterspackman

plugins:
    - search
    - mkdocstrings
    - gen-files:
        scripts:
        - scripts/mkdocs_gen_ref_pages.py
    - literate-nav:
        nav_file: SUMMARY.md


markdown_extensions:
    - codehilite

nav:
    - Home: index.md
    - Overview: 
        - Shape Descriptors: shape_descriptors.md
        - Notes on Parallelization: parallel.md
    - Programming Interface (API): reference/
