site_name: chmpy
site_url: https://peterspackman.github.io/chmpy/
repo_url: https://github.com/peterspackman/chmpy
repo_name: peterspackman/chmpy

theme:
    name: material
    logo: assets/chmpy_logo_small_no_text_dark.png
    features:
        - content.code.copy
    palette:
        primary: blue grey
        scheme: preference
    font:
        text: Helvetica
        code: Noto Sans Mono

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/peterspackman

plugins:
    - search
    - mkdocstrings
    - gen-files:
        scripts:
        - scripts/mkdocs_gen_ref_pages.py
    - literate-nav:
        nav_file: SUMMARY.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
    - Home: index.md
    - Overview: 
        - Shape Descriptors: shape_descriptors.md
        - Notes on Parallelization: parallel.md
    - Programming Interface (API): reference/
