name: Release
on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: wheels

    - name: Release
      uses: softprops/action-gh-release@v1
      with: 
        files: | 
          wheels/*


  upload_all:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: wheels 
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1
